# Generated by Django 2.2.10 on 2020-11-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201117_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
