# Generated by Django 2.2.10 on 2020-11-17 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20201117_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='descritption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 21, 9, 2, 697374)),
        ),
    ]
