# Generated by Django 2.2.10 on 2020-11-18 11:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20201117_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 11, 56, 13, 432431)),
        ),
    ]
