# Generated by Django 2.2.10 on 2020-11-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20201118_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'Text answer'), ('POA', 'Pick one answer'), ('PMA', 'Pick multiple answer')], default='TXT', max_length=3),
        ),
    ]
