# Generated by Django 2.2.10 on 2021-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20210728_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
